#
# Generated - do not edit!
#
# NOCDDL
#
CND_BASEDIR=`pwd`
# GOOGLE_IOT configuration
CND_ARTIFACT_DIR_GOOGLE_IOT=dist/GOOGLE_IOT/production
CND_ARTIFACT_NAME_GOOGLE_IOT=AVRIoT.X.production.hex
CND_ARTIFACT_PATH_GOOGLE_IOT=dist/GOOGLE_IOT/production/AVRIoT.X.production.hex
CND_PACKAGE_DIR_GOOGLE_IOT=${CND_DISTDIR}/GOOGLE_IOT/package
CND_PACKAGE_NAME_GOOGLE_IOT=avriot.x.tar
CND_PACKAGE_PATH_GOOGLE_IOT=${CND_DISTDIR}/GOOGLE_IOT/package/avriot.x.tar
